[theme]
base = "light"
primaryColor = "#D71920"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F4F5"
textColor = "#27272A"
font = "sans serif"

[server]
headless = true
enableXsrfProtection = true
enableCORS = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
